#Project information
Project: CEPC-CALO
Contact: Zhen Wang < wangz1996@sjtu.edu.cn >


Global:
        useseed: False # default: system time in nano-second
        seed: 1234


        usemac: False # Currently not applicable
        mac: ./vis.mac


        output: ./hcal_muon_100GeV_2cm_10w.root # Output root file name
        beamon: 100000
#Construct Calorimeter
ECAL:
        build: False


HCAL:
        build: True


#Particle source setup
Source:
        particle: mu+
        energy: 100.  # Unit is in GeV
        position: [ 2, 2, 0.]   # Unit is in cm
        direction: [ 0., 0., 1.]
#Verbose
Verbose:
        run: 0
        control: 0
        event: 0
        tracking: 0
